name = "Resource Pack Maker"
author = "Alfakynz"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "000ff06474ba98355dfd3187495e47c422b2f4c113562714520638f01004c884"

[versions]
fabric = "0.18.6"
minecraft = "1.20.1"
