name = "Resource Pack Maker"
author = "Alfakynz"
version = "1.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3715f0d39f0e4106365b8336817d6519eecf26927bf87988eceab528fb3f08eb"

[versions]
fabric = "0.19.2"
minecraft = "1.20.1"
