name = "Resource Pack Maker"
author = "Alfakynz"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "420689c1117e3b5f32aa94d1ccd6338d0ae221bca11e5a1c88df40dc91bab4d6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
