name = "Resource Pack Maker"
author = "Alfakynz"
version = "1.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "effb06ffd92acb64e4c1b8cdf1c8e2c8b0fb1fb274e3c41e1f286228a91597c7"

[versions]
fabric = "0.18.6"
minecraft = "1.21.1"
